In [1]:
import os
from pathlib import Path

import duckdb
import geopandas as gpd
import numpy as np
import pandas as pd

In [2]:
data_path = Path(os.environ["DATA_PATH"])
scripts_path = Path("./scripts")

In [5]:
with (scripts_path / "01_registro.sql").open(encoding="utf8") as f:
    registro_query = f.read()
    duckdb.sql(registro_query)

df_orig = (
    pd.read_parquet("data/processed/choiceset.parquet")
    .dropna(subset=["partida_main"])
    .assign(geometry=lambda df: gpd.points_from_xy(df["longitud"], df["latitud"]))
    .drop(columns=["longitud", "latitud"])
    .pipe(gpd.GeoDataFrame, geometry="geometry", crs="EPSG:4326")
    .to_crs("EPSG:6372")
)

In [9]:
df_orig.loc[lambda df: df["privada"].isna()]["fraccionamiento"].value_counts()

fraccionamiento
Parajes De Puebla               182714
Privadas Condesa                 59985
Valle Del Progreso               55348
Rincones De Puebla               52803
Angeles De Puebla                10637
Valle De Puebla 5Ta Secc.         8773
Huertas del Colorado              6345
Valle Oriente                     4133
VILLANOVA                         3808
Quinta Granada                    3567
Privadas Campestre                1849
COLONIA BALBUENA                  1637
Caminos Del Sol                   1465
San Andres                        1121
PORTICOS DEL VALLE                 912
COLONIA GRANJAS AGRICOLAS          645
Gran Foresta                       267
LA RIOJA SECCION CASTILLAUNA       263
Foresta Life                       164
Bonaterra Residencial              119
Corceles Residencial                95
Ibiza Residencial                   82
Quinta Granada 3                    71
Residencial Natura                  55
Name: count, dtype: int64

In [8]:
df_orig

,is_main,partida_main,partida,folio,inmobiliaria,fecha_operacion,fecha_partida,valor_operacion,edad,lote,manzana,privada,direccion,acreedor,comprador,mts_superficie,fraccionamiento,geometry
0,1,5894191,5894191,1582847,Exe Inmobiliaria,2020-01-02,2020-03-24,640000.000,NaN,67,161,GANTE,DESARROLLO URBANO LA CONDESA SECCION GANTE,BANCARIO,INDIVIDUO,120.050003,Privadas Condesa,POINT (1240838.144 2338909.247)
1,0,5903701,5894191,1582847,Exe Inmobiliaria,2020-01-02,2020-03-24,640000.000,NaN,67,161,GANTE,DESARROLLO URBANO LA CONDESA SECCION GANTE,BANCARIO,INDIVIDUO,120.050003,Privadas Condesa,POINT (1240838.144 2338909.247)
2,0,5896400,5894191,1582847,Exe Inmobiliaria,2020-01-02,2020-03-24,640000.000,NaN,67,161,GANTE,DESARROLLO URBANO LA CONDESA SECCION GANTE,BANCARIO,INDIVIDUO,120.050003,Privadas Condesa,POINT (1240838.144 2338909.247)
3,0,5898756,5894191,1582847,Exe Inmobiliaria,2020-01-02,2020-03-24,640000.000,NaN,67,161,GANTE,DESARROLLO URBANO LA CONDESA SECCION GANTE,BANCARIO,INDIVIDUO,120.050003,Privadas Condesa,POINT (1240838.144 2338909.247)
4,0,5900352,5894191,1582847,Exe Inmobiliaria,2020-01-02,2020-03-24,640000.000,NaN,67,161,GANTE,DESARROLLO URBANO LA CONDESA SECCION GANTE,BANCARIO,INDIVIDUO,120.050003,Privadas Condesa,POINT (1240838.144 2338909.247)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
974960,0,6041373,6046739,1703673,Exe Inmobiliaria,2024-12-31,2025-04-01,906124.375,29.0,13,264,OLEAGA,DESARROLLO URBANO LA CONDESA SECCION OLEAGA,FOVISSSTE,INDIVIDUO,120.050003,Privadas Condesa,POINT (1239864.058 2339730.678)
974961,0,6046458,6046739,1703673,Exe Inmobiliaria,2024-12-31,2025-04-01,906124.375,29.0,13,264,OLEAGA,DESARROLLO URBANO LA CONDESA SECCION OLEAGA,FOVISSSTE,INDIVIDUO,120.050003,Privadas Condesa,POINT (1239864.058 2339730.678)
974962,0,6048786,6046739,1703673,Exe Inmobiliaria,2024-12-31,2025-04-01,906124.375,29.0,13,264,OLEAGA,DESARROLLO URBANO LA CONDESA SECCION OLEAGA,FOVISSSTE,INDIVIDUO,120.050003,Privadas Condesa,POINT (1239864.058 2339730.678)
974963,0,6049029,6046739,1703673,Exe Inmobiliaria,2024-12-31,2025-04-01,906124.375,29.0,13,264,OLEAGA,DESARROLLO URBANO LA CONDESA SECCION OLEAGA,FOVISSSTE,INDIVIDUO,120.050003,Privadas Condesa,POINT (1239864.058 2339730.678)
974964,0,6049768,6046560,1703716,Exe Inmobiliaria,2024-12-31,2025-03-31,755000.000,NaN,8,265,OLEAGA,DESARROLLO URBANO LA CONDESA SECCION OLEAGA,CONTADO,INDIVIDUO,120.050003,Privadas Condesa,POINT (1239864.058 2339730.678)

In [12]:
df_orig.loc[lambda x: x["inmobiliaria"].fillna("").str.casefold().str.contains("exe")][
    "fraccionamiento"
].value_counts()

fraccionamiento
Privadas Condesa        547479
Fontalba Residencial      1427
Name: count, dtype: int64

In [20]:
df_orig

,is_main,partida_main,partida,folio,inmobiliaria,fecha_operacion,fecha_partida,valor_operacion,edad,lote,manzana,privada,direccion,acreedor,comprador,mts_superficie,fraccionamiento,geometry
0,1,5894191,5894191.0,1582847.0,Exe Inmobiliaria,2020-01-02,2020-03-24,640000.0,NaN,67,161,GANTE,DESARROLLO URBANO LA CONDESA SECCION GANTE,BANCARIO,INDIVIDUO,120.050003,Privadas Condesa,POINT (1240838.144 2338909.247)
1,0,5914406,5894191.0,1582847.0,Exe Inmobiliaria,2020-01-02,2020-03-24,640000.0,NaN,67,161,GANTE,DESARROLLO URBANO LA CONDESA SECCION GANTE,BANCARIO,INDIVIDUO,120.050003,Privadas Condesa,POINT (1240838.144 2338909.247)
2,0,5900352,5894191.0,1582847.0,Exe Inmobiliaria,2020-01-02,2020-03-24,640000.0,NaN,67,161,GANTE,DESARROLLO URBANO LA CONDESA SECCION GANTE,BANCARIO,INDIVIDUO,120.050003,Privadas Condesa,POINT (1240838.144 2338909.247)
3,0,5892416,5894191.0,1582847.0,Exe Inmobiliaria,2020-01-02,2020-03-24,640000.0,NaN,67,161,GANTE,DESARROLLO URBANO LA CONDESA SECCION GANTE,BANCARIO,INDIVIDUO,120.050003,Privadas Condesa,POINT (1240838.144 2338909.247)
4,0,5895108,5894191.0,1582847.0,Exe Inmobiliaria,2020-01-02,2020-03-24,640000.0,NaN,67,161,GANTE,DESARROLLO URBANO LA CONDESA SECCION GANTE,BANCARIO,INDIVIDUO,120.050003,Privadas Condesa,POINT (1240838.144 2338909.247)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
834192,0,6006465,NaN,NaN,None,None,None,NaN,NaN,None,None,None,None,None,None,NaN,None,POINT (NaN NaN)
834193,0,6008580,NaN,NaN,None,None,None,NaN,NaN,None,None,None,None,None,None,NaN,None,POINT (NaN NaN)
834194,0,6008604,NaN,NaN,None,None,None,NaN,NaN,None,None,None,None,None,None,NaN,None,POINT (NaN NaN)
834195,0,6013870,NaN,NaN,None,None,None,NaN,NaN,None,None,None,None,None,None,NaN,None,POINT (NaN NaN)
834196,0,5913487,NaN,NaN,None,None,None,NaN,NaN,None,None,None,None,None,None,NaN,None,POINT (NaN NaN)

In [13]:
df_orig["fraccionamiento"].value_counts()

fraccionamiento
Privadas Condesa             549452
Parajes De Puebla            158235
Valle Del Progreso            49941
Rincones De Puebla            46382
Angeles De Puebla              8091
Huertas del Colorado           5721
Valle De Puebla 5Ta Secc.      4046
Valle Oriente                  3948
Quinta Granada                 3037
Fontalba Residencial           1427
Privadas Campestre             1327
Caminos Del Sol                1175
San Andres                      991
Corceles Residencial             89
Ibiza Residencial                77
Quinta Granada 3                 70
Foresta Life                     48
Gran Foresta                     18
Bonaterra Residencial             2
Residencial Natura                1
Name: count, dtype: int64

In [41]:
df_init = (
    pd.read_excel(
        data_path / "processing" / "RPPC_vivienda-interes-social-nueva_2020-2024.xlsx",
    )
    .rename(
        columns={
            "Inmobiliaria": "inmobiliaria",
            "Lote": "lote",
            "Manzana": "manzana",
            "Fraccionamiento": "fraccionamiento",
            "Direccion": "direccion",
            "Razón social": "razon_social",
            "Comprador": "comprador",
            "Acreedor": "acreedor",
            "Acreedores": "acreedores",
            "Tipo de vivienda": "tipo_vivienda",
            "Categoría": "categoria",
            "Folio real": "folio",
            "Fecha de operacion": "fecha_operacion",
            "Competencia actual": "competencia_actual",
            "Valor de operacion": "valor_operacion",
            "Monto de crédito": "monto_credito",
            "Fecha de partida": "fecha_partida",
            "Partida": "partida",
            "Superficie": "mts_superficie",
            "Edad": "edad",
            "Latitud": "latitud",
            "Longitud": "longitud",
            "Mercado Exe": "mercado_exe",
        },
    )
    .assign(
        folio=lambda df: pd.to_numeric(df["folio"], errors="coerce").astype("Int64"),
        fecha_operacion=lambda df: pd.to_datetime(df["fecha_operacion"]),
        competencia_actual=lambda df: (
            df["competencia_actual"].str.lower().eq("sí").astype("Int64")
        ),
        valor_operacion=lambda df: pd.to_numeric(
            df["valor_operacion"],
            errors="coerce",
        ),
        monto_credito=lambda df: pd.to_numeric(df["monto_credito"], errors="coerce"),
        fecha_partida=lambda df: pd.to_datetime(df["fecha_partida"]),
        partida=lambda df: pd.to_numeric(df["partida"], errors="coerce").astype(
            "Int64",
        ),
        mts_superficie=lambda df: pd.to_numeric(df["mts_superficie"], errors="coerce"),
        edad=lambda df: pd.to_numeric(df["edad"], errors="coerce").astype("Int64"),
        latitud=lambda df: pd.to_numeric(df["latitud"], errors="coerce"),
        longitud=lambda df: pd.to_numeric(df["longitud"], errors="coerce"),
        mercado_exe=lambda df: df["mercado_exe"].str.lower().eq("sí"),
    )
    .assign(
        fraccionamiento=lambda df: (
            df["fraccionamiento"]
            .str.strip()
            .replace(
                {
                    r"^FRACCIONAMIENTO VILLANOVA.*": "VILLANOVA",
                    r".*PORTICOS DEL VALLE.*": "PORTICOS DEL VALLE",
                },
                regex=True,
            )
            .where(
                lambda x: ~x.str.startswith("FRAC"),
                lambda x: (
                    x.str.replace("FRACCIONAMIENTO", "")
                    .str.replace("FRACC", "")
                    .str.replace("FRACCTO", "")
                    .str.replace("FRACTO", "")
                    .str.strip()
                ),
            )
            .where(
                lambda x: ~x.str.startswith("COLONIA BALBUENA"),
                lambda x: x.str.replace("DE MEXICALI BC DENTRO DE LA", "").str.strip(),
            )
            .where(
                lambda x: ~x.str.startswith("COLONIA GRANJAS AGRICOLAS"),
                lambda x: x.str.replace(
                    "FOLIO REAL 1598810 DE MEXICALI BC",
                    "",
                ).str.strip(),
            )
        ),
        coords=lambda df: df["fraccionamiento"].map(
            {
                "Angeles De Puebla": (32.564770, -115.339935),
                "COLONIA BALBUENA": (32.630970, -115.472679),
                "Corceles Residencial": (32.567668, -115.469794),
                "Gran Foresta": (32.563446, -115.434414),
                "Huertas del Colorado": (32.563662, -115.411109),
                "LA RIOJA SECCION CASTILLAUNA": (32.656198, -115.364974),
                "PORTICOS DEL VALLE": (32.595718, -115.438633),
                "Parajes De Puebla": (32.557625, -115.346180),
                "Quinta Granada": (32.572234, -115.469416),
                "Quinta Granada 3": (32.567764, -115.473000),
                "San Andres": (32.577850, -115.424811),
                "Valle Oriente": (32.571884, -115.361330),
                "Privadas Condesa": (32.595546, -115.344834),
            },
        ),
        new_lat=lambda df: df["coords"].apply(
            lambda x: x[0] if not pd.isna(x) else np.nan,
        ),
        new_lon=lambda df: df["coords"].apply(
            lambda x: x[1] if not pd.isna(x) else np.nan,
        ),
        latitud=lambda df: df["latitud"].fillna(df["new_lat"]),
        longitud=lambda df: df["longitud"].fillna(df["new_lon"]),
        privada=lambda df: (
            df["direccion"]
            .str.strip()
            .where(
                lambda x: ~x.str.startswith("DESARROLLO URBANO LA CONDESA"),
                lambda x: x.str.replace(
                    r"DESARROLLO URBANO LA CONDESA SECCI(O|Ó)N",
                    "WANTED_",
                    regex=True,
                ).str.strip(),
            )
            .where(
                lambda x: (
                    ~x.str.startswith(
                        "DESARROLLO URBANO VICTORIA RESIDENCIAL SEGUNDA SECCION",
                    )
                ),
                lambda x: x.str.replace(
                    "DESARROLLO URBANO VICTORIA RESIDENCIAL SEGUNDA SECCION",
                    "WANTED_VICTORIA",
                ).str.strip(),
            )
            .where(lambda x: x.str.startswith("WANTED_"), None)
            .str.replace("WANTED_", "")
            .str.strip()
        ),
        direccion=lambda df: (
            df["direccion"].str.replace("LOCALIZACION:", "").str.strip()
        ),
    )
    .drop(columns=["coords", "new_lat", "new_lon"])
    .query("~fraccionamiento.str.match(r'.*PUERTO DE SAN FELIPE.*')")
)

In [ ]:
df_init["geometry_existing"]

0                   POINT (NaN NaN)
1                   POINT (NaN NaN)
2       POINT (-115.57941 32.58832)
3       POINT (-115.57941 32.58832)
4       POINT (-115.57941 32.58832)
                   ...
7824                POINT (NaN NaN)
7825                POINT (NaN NaN)
7826                POINT (NaN NaN)
7827                POINT (NaN NaN)
7828                POINT (NaN NaN)
Name: geometry_existing, Length: 7812, dtype: geometry