In [15]:
import biogeme.database as db
import pandas as pd
from biogeme.expressions import Variable

In [16]:
df_merged = pd.read_parquet("./merged.parquet")

In [17]:
df_merged

,fraccionamiento,fecha_operacion,valor_operacion,monto_credito,tree_coverage_frac,urbanized_area_frac,jobs,jobs_manufacture,accessibility,travel_time_to_center
0,la rioja seccion castilla,2021-02-11,600000.00,NaN,0.005556,0.147654,195386.822185,47079.409561,0.120852,687.384224
1,la rioja seccion castilla,2020-04-20,893688.06,NaN,0.005556,0.147654,195386.822185,47079.409561,0.120852,687.384224
2,valle del progreso,2024-12-30,680000.00,1293806.96,0.000000,0.088346,127424.635240,24271.392074,0.151123,739.536661
3,valle del progreso,2024-12-23,680000.00,1300408.02,0.000000,0.088346,127424.635240,24271.392074,0.151123,739.536661
4,valle del progreso,2024-12-23,680000.00,1234397.46,0.000000,0.088346,127424.635240,24271.392074,0.151123,739.536661
...,...,...,...,...,...,...,...,...,...,...
7128,parajes de puebla,2020-01-10,426000.00,425057.32,0.001291,0.031716,161912.636696,42281.558197,0.113119,1125.239429
7129,parajes de puebla,2020-01-10,426000.00,364726.17,0.001291,0.031716,161912.636696,42281.558197,0.113119,1125.239429
7130,privadas campestre,2020-01-10,920000.00,NaN,0.000000,0.021990,219639.503302,55048.569545,0.069705,656.870732
7131,angeles de puebla,2020-01-08,483000.00,447475.68,0.017377,0.126476,170296.140736,44032.751472,0.187450,1045.492492
7132,privadas campestre,2020-01-06,924000.00,739200.00,0.000000,0.021990,219639.503302,55048.569545,0.069705,656.870732

In [11]:
database = db.Database("col", df_col.drop(columns=["geometry"]))

In [14]:
var_tree_coverage_frac = Variable("tree_coverage_frac")
var_urbanized_area_frac = Variable("urbanized_area_frac")
var_jobs = Variable("jobs")
var_jobs_manufacture = Variable("jobs_manufacture")
var_accessibility = Variable("accessibility")
var_travel_time_to_center = Variable("travel_time_to_center")

In [3]:
df_col

,geometry,tree_coverage_frac,urbanized_area_frac,jobs,jobs_manufacture,accessibility,travel_time_to_center
COLONIAS,,,,,,,
18 de marzo,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00!\x00\x0...,0.056107,0.174922,241204.752451,57880.874261,0.324100,535.088783
27 de enero magisterial,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00\x07\x00...,0.004160,0.005316,171961.812111,43812.198884,0.119727,1082.647406
27 de septiembre,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00\x07\x00...,0.043113,0.340007,211809.756821,43198.625223,0.457595,263.645287
5 de julio,"b'\x01\x03\x00\x00\x00\x01\x00\x00\x00""\x00\x0...",0.003377,0.054020,229047.178174,54269.749518,0.147189,535.818625
adara,"b""\x01\x03\x00\x00\x00\x01\x00\x00\x00\x1c\x00...",0.000060,0.004049,227048.338938,56019.425899,0.395900,680.977785
...,...,...,...,...,...,...,...
xochimilco,b'\x01\x03\x00\x00\x00\x01\x00\x00\x008\x00\x0...,0.029918,0.133111,236845.387640,55502.126685,0.244676,488.644784
zacatecas,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00\x17\x00...,0.047314,0.386534,242780.262293,51427.071036,0.470520,252.345085
zona industrial,b'\x01\x06\x00\x00\x00\x06\x00\x00\x00\x01\x03...,0.033303,0.211268,239568.370273,51387.528938,0.427008,252.898619
zona progreso popular,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00\n\x00\x...,0.003656,0.161278,111979.214210,19248.674581,0.295815,744.187779
zona urbana xochimilco,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00\x10\x00...,0.031545,0.107311,201276.119988,44331.756155,0.172672,568.690178